### ISSUE TITLE
Requirements.txt file? 

### ISSUE THREAD

**Issue by Kyu** [llu13701/sms_analysis#1]
For simpler installation, the repo should have a requirements.txt file that lists each non standard pip module needed, so that one could simply run `pip install -r requirements.txt`  

the file I have in mind would look like 
```
pandas
matplotlib
emoji
spacy
nltk
transformers
torch

https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz#egg=en_core_web_sm
https://github.com/explosion/spacy-models/releases/download/en_vectors_web_lg-2.3.1/en_vectors_web_lg-2.3.1.tar.gz#egg=en_vectors_web_lg
```  

https://spacy.io/usage/models#models-download

**Comment by llu13701** [comment]
thanks! just added
